name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  format:
    env:
      MIX_ENV: test
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-elixir@v1
        with:
          otp-version: 23.1.5
          elixir-version: 1.11.3

      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix deps.unlock --check-unused
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors

  test:
    env:
      MIX_ENV: test
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-elixir@v1
        with:
          otp-version: 23.1.5
          elixir-version: 1.11.3

      - run: mix deps.get
      - run: mix deps.compile
      - run: mix test
