name: CI

on: [push, pull_request]

jobs:
  test:
    env:
      MIX_ENV: test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27.2
          elixir-version: 1.17.3

      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix deps.unlock --check-unused
      - run: MIX_ENV=test mix compile --warnings-as-errors
      - run: mix test
